import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import MainProvider from "@/providers";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({ style: "normal", weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body
					className={cn(
						"w-screen h-full antialiased bg-blue-100 tracking-tight leading-relaxed",
						poppins.className
					)}
				>
					<MainProvider>
						<main className="w-screen flex flex-col items-center justify-between">
							{children}
						</main>
					</MainProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
