import {cn} from '@/lib/utils'
import MainProvider from '@/providers'
import {ClerkProvider} from '@clerk/nextjs'
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import {Toaster} from 'sonner'
import './globals.css'

const poppins = Poppins({style: 'normal', weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            'w-full h-full antialiased min-h-screen tracking-tight leading-relaxed',
            poppins.className,
          )}
        >
          <MainProvider>
            <Toaster />
            {children}
          </MainProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
